/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsm.ia.mcp;

/**
 *
 * @author Patrick Guerra
 */
public class userInterface extends javax.swing.JFrame {
    public static double[][] tabelaTreinamento = {{0,0,0},{0,0,0},{0,0,0},{0,0,0}};
    public static double[] w = {0,0}; //pesos
    public static final double c = 0.5;
    public static double limiar = 0.5;
    public Treinamento treinamento = new Treinamento(tabelaTreinamento, w, limiar, c);
    public RedeNeural redeNeural = new RedeNeural(treinamento);
    /**
     * Creates new form userInterface
     */
    public userInterface() {
        initComponents();
        salvaTabelaTreinamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTFi1j1 = new javax.swing.JTextField();
        jTFi1j2 = new javax.swing.JTextField();
        jTFi1j3 = new javax.swing.JTextField();
        jTFi2j1 = new javax.swing.JTextField();
        jTFi2j2 = new javax.swing.JTextField();
        jTFi2j3 = new javax.swing.JTextField();
        jTFi3j1 = new javax.swing.JTextField();
        jTFi3j2 = new javax.swing.JTextField();
        jTFi3j3 = new javax.swing.JTextField();
        jTFi4j1 = new javax.swing.JTextField();
        jTFi4j2 = new javax.swing.JTextField();
        jTFi4j3 = new javax.swing.JTextField();
        jBtnTreinamentoAND = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTFteste1 = new javax.swing.JTextField();
        jTFteste2 = new javax.swing.JTextField();
        jTFteste3 = new javax.swing.JTextField();
        jBtnTeste = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Treinamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Porta AND", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jTFi1j1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi1j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi1j1.setText("0");

        jTFi1j2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi1j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi1j2.setText("0");

        jTFi1j3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi1j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi1j3.setText("0");

        jTFi2j1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi2j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi2j1.setText("0");

        jTFi2j2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi2j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi2j2.setText("1");

        jTFi2j3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi2j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi2j3.setText("0");

        jTFi3j1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi3j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi3j1.setText("1");

        jTFi3j2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi3j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi3j2.setText("0");

        jTFi3j3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi3j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi3j3.setText("0");

        jTFi4j1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi4j1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi4j1.setText("1");

        jTFi4j2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi4j2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi4j2.setText("1");

        jTFi4j3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFi4j3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFi4j3.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFi4j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFi4j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFi4j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFi1j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi1j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi1j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFi2j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi2j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi2j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFi3j1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi3j2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTFi3j3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFi1j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi1j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi1j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFi2j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi2j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi2j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFi3j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi3j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi3j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFi4j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi4j2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFi4j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnTreinamentoAND.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jBtnTreinamentoAND.setText("Treinamento AND");
        jBtnTreinamentoAND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTreinamentoANDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jBtnTreinamentoAND)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnTreinamentoAND)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Teste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Digite os dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jTFteste1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFteste1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFteste1.setText("1");

        jTFteste2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFteste2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFteste2.setText("1");

        jTFteste3.setBackground(new java.awt.Color(204, 204, 255));
        jTFteste3.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jTFteste3.setForeground(new java.awt.Color(0, 0, 0));
        jTFteste3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFteste3.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFteste1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFteste2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFteste3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFteste1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFteste2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFteste3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnTeste.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jBtnTeste.setText("Teste");
        jBtnTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jBtnTeste)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnTeste)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvaTabelaTreinamento(){
        tabelaTreinamento[0][0] = Double.parseDouble(jTFi1j1.getText());
        tabelaTreinamento[0][1] = Double.parseDouble(jTFi1j2.getText());
        tabelaTreinamento[0][2] = Double.parseDouble(jTFi1j3.getText());
        tabelaTreinamento[1][0] = Double.parseDouble(jTFi2j1.getText());
        tabelaTreinamento[1][1] = Double.parseDouble(jTFi2j2.getText());
        tabelaTreinamento[1][2] = Double.parseDouble(jTFi2j3.getText());
        tabelaTreinamento[2][0] = Double.parseDouble(jTFi3j1.getText());
        tabelaTreinamento[2][1] = Double.parseDouble(jTFi3j2.getText());
        tabelaTreinamento[2][2] = Double.parseDouble(jTFi3j3.getText());
        tabelaTreinamento[3][0] = Double.parseDouble(jTFi4j1.getText());
        tabelaTreinamento[3][1] = Double.parseDouble(jTFi4j2.getText());
        tabelaTreinamento[3][2] = Double.parseDouble(jTFi4j3.getText());
    }
    
    private void jBtnTreinamentoANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTreinamentoANDActionPerformed
        // TODO add your handling code here:
        salvaTabelaTreinamento();
        treinamento.executaTreinamento();
    }//GEN-LAST:event_jBtnTreinamentoANDActionPerformed

    private void jBtnTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTesteActionPerformed
        // TODO add your handling code here:
        double x1 = Double.parseDouble(jTFteste1.getText());
        double x2 = Double.parseDouble(jTFteste2.getText());
        double sd = Double.parseDouble(jTFteste3.getText());
        redeNeural.exibeSaida(x1, x2, sd);
    }//GEN-LAST:event_jBtnTesteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnTeste;
    private javax.swing.JButton jBtnTreinamentoAND;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTFi1j1;
    private javax.swing.JTextField jTFi1j2;
    private javax.swing.JTextField jTFi1j3;
    private javax.swing.JTextField jTFi2j1;
    private javax.swing.JTextField jTFi2j2;
    private javax.swing.JTextField jTFi2j3;
    private javax.swing.JTextField jTFi3j1;
    private javax.swing.JTextField jTFi3j2;
    private javax.swing.JTextField jTFi3j3;
    private javax.swing.JTextField jTFi4j1;
    private javax.swing.JTextField jTFi4j2;
    private javax.swing.JTextField jTFi4j3;
    private javax.swing.JTextField jTFteste1;
    private javax.swing.JTextField jTFteste2;
    private javax.swing.JTextField jTFteste3;
    // End of variables declaration//GEN-END:variables
}
