/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsm.poo.cadastro.ui;
import br.ufsm.poo.cadastro.negocio.BDMemoriaNegocio;
import br.ufsm.poo.cadastro.dados.ProdutoModelo;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author patri
 */
public class TelaListagem extends javax.swing.JDialog {
    BDMemoriaNegocio bd;
    int index = 0;
    int indexAnt = 0;
    /**
     * Creates new form TelaListagem
     */
    public TelaListagem(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        try {
            bd = new BDMemoriaNegocio();
            ProdutoModelo produtoAtual = bd.getRegistro(index);
            jTFNomeProduto.setText(produtoAtual.getNomeProduto());
            jTAEspecificacaoT.setText(produtoAtual.getEspecificacaoTecnica());
            jTFPrecoVenda.setText(String.valueOf(produtoAtual.getPrecoVenda()));
            jTFPrecoCusto.setText(String.valueOf(produtoAtual.getPrecoCusto()));
            if(produtoAtual.getHabilitarVenda() == 0){
                jTFHabilitarVendas.setText("Habilitado");
            }else if(produtoAtual.getHabilitarVenda() == 1){
                jTFHabilitarVendas.setText("Desabilitado");
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaListagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEspecificacaoT = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTFPrecoVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFHabilitarVendas = new javax.swing.JTextField();
        jTFPrecoCusto = new javax.swing.JTextField();
        jSProduto = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagens dos Produtos");

        jLabel5.setText("Habilitar Vendas:");

        jLabel1.setText("Nome do Produto:");

        jTFNomeProduto.setEditable(false);

        jLabel2.setText("Especificação Técnica:");

        jTAEspecificacaoT.setEditable(false);
        jTAEspecificacaoT.setColumns(20);
        jTAEspecificacaoT.setRows(5);
        jScrollPane1.setViewportView(jTAEspecificacaoT);

        jLabel3.setText("Preço de venda:");

        jTFPrecoVenda.setEditable(false);

        jLabel4.setText("Preço de custo:");

        jTFHabilitarVendas.setEditable(false);

        jTFPrecoCusto.setEditable(false);

        jSProduto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSProdutoStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jTFHabilitarVendas)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jTFPrecoCusto)))
                    .addComponent(jSProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFHabilitarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSProdutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSProdutoStateChanged
        // TODO add your handling code here:
        indexAnt = index;
        index = Integer.valueOf(jSProduto.getValue().toString());
        if(index < bd.getContador()){
            ProdutoModelo produtoAtual = bd.getRegistro(index);
            jTFNomeProduto.setText(produtoAtual.getNomeProduto());
            jTAEspecificacaoT.setText(produtoAtual.getEspecificacaoTecnica());
            jTFPrecoVenda.setText(String.valueOf(produtoAtual.getPrecoVenda()));
            jTFPrecoCusto.setText(String.valueOf(produtoAtual.getPrecoCusto()));
            if(produtoAtual.getHabilitarVenda() == 0){
                jTFHabilitarVendas.setText("Habilitado");
            }else if(produtoAtual.getHabilitarVenda() == 1){
                jTFHabilitarVendas.setText("Desabilitado");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Nao existe nenhum produto com esse codigo!");
            index = indexAnt;
            jTFNomeProduto.setText("");
            jTAEspecificacaoT.setText("");
            jTFPrecoVenda.setText("");
            jTFPrecoCusto.setText("");
            jTFHabilitarVendas.setText("");
        }
    }//GEN-LAST:event_jSProdutoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaListagem dialog = new TelaListagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSConta;
    private javax.swing.JSpinner jSConta1;
    private javax.swing.JSpinner jSConta2;
    private javax.swing.JSpinner jSProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAEspecificacaoT;
    private javax.swing.JTextField jTFHabilitarVendas;
    private javax.swing.JTextField jTFNomeProduto;
    private javax.swing.JTextField jTFPrecoCusto;
    private javax.swing.JTextField jTFPrecoVenda;
    // End of variables declaration//GEN-END:variables
}
