/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsm.Conta.ui;
import br.ufsm.Conta.negocio.ContaNegocio;
import javax.swing.JOptionPane;

/**
 *
 * @author patri
 */
public class ContaSacar extends javax.swing.JFrame {
    ContaNegocio negocio;
    int codContaAtual;
    /**
     * Creates new form ContaSacar
     */
    public ContaSacar(ContaNegocio neg, int cod){
        initComponents();
        negocio = neg;
        codContaAtual = cod;
        jLSaldo.setText(String.valueOf(negocio.getDados(codContaAtual).getSaldo()));
        jLLimite.setText(String.valueOf(negocio.getDados(codContaAtual).getLimite()));
    }
    public ContaSacar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBSacar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        jLLimite = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFSaque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Limite: R$");

        jBSacar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBSacar.setText("Realizar Saque");
        jBSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSacarActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Saldo: R$");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Saque");

        jLSaldo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLSaldo.setText("0.0");

        jLLimite.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLLimite.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("Saque: R$");

        jTFSaque.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLLimite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBSacar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFSaque)))
                .addGap(0, 127, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBSacar, jBVoltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLSaldo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLLimite))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSacar)
                    .addComponent(jBVoltar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSacarActionPerformed
        // TODO add your handling code here:
        double saque = Double.valueOf(jTFSaque.getText());
        double saldoAtual = negocio.getDados(codContaAtual).getSaldo();
        double limiteAtual = negocio.getDados(codContaAtual).getLimite();
        double novoSaldo;
        double saldoComLimite;
        double novoLimite;
        double saldoFinal;
        if(saldoAtual <= 0){
            if(saque > limiteAtual){
                JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                jTFSaque.setText("");
            }else{
                novoSaldo = saldoAtual - saque;
                novoLimite = limiteAtual - saque;
                if(limiteAtual >= 0){
                    saldoFinal = novoSaldo;
                    jLLimite.setText(String.valueOf(novoLimite));
                    jLSaldo.setText(String.valueOf(saldoFinal));
                    negocio.getDados(codContaAtual).setSaldo(saldoFinal);
                    negocio.getDados(codContaAtual).setLimite(novoLimite);
                    jTFSaque.setText("");
                    JOptionPane.showMessageDialog(null,"Saque Realizado Com Sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                    jTFSaque.setText("");
                }
            }
        }else{
            novoSaldo = saldoAtual - saque;
            if(novoSaldo >= 0){
                negocio.getDados(codContaAtual).setSaldo(novoSaldo);
                jLSaldo.setText(String.valueOf(novoSaldo));
                jTFSaque.setText("");
                JOptionPane.showMessageDialog(null,"Saque Realizado Com Sucesso!");
            }else{
                novoLimite = limiteAtual + novoSaldo;
                saldoFinal = novoSaldo; 
                if(novoLimite >= 0){
                    negocio.getDados(codContaAtual).setSaldo(saldoFinal);
                    negocio.getDados(codContaAtual).setLimite(novoLimite);
                    jTFSaque.setText("");
                    JOptionPane.showMessageDialog(null,"Saque Realizado Com Sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                    jTFSaque.setText("");
                }
            }
        }
        jLLimite.setText(String.valueOf(negocio.getDados(codContaAtual).getLimite()));
        jLSaldo.setText(String.valueOf(negocio.getDados(codContaAtual).getSaldo()));
    }//GEN-LAST:event_jBSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaSacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaSacar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSacar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLLimite;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFSaque;
    // End of variables declaration//GEN-END:variables
}
