/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsm.Conta.ui;

import br.ufsm.Conta.negocio.ContaNegocio;
import javax.swing.JOptionPane;

/**
 *
 * @author patri
 */
public class ContaTransferir extends javax.swing.JFrame {
    ContaNegocio negocio;
    int codContaAtual;
    /**
     * Creates new form ContaTransferir
     */
    public ContaTransferir(ContaNegocio neg, int ind){
        initComponents();
        negocio = neg;
        codContaAtual = ind;
        jLSaldo.setText(String.valueOf(negocio.getDados(codContaAtual).getSaldo()));
    }
    public ContaTransferir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFTransferencia = new javax.swing.JTextField();
        jBVoltar = new javax.swing.JButton();
        jSConta = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jBTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Transferencia");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Saldo: R$");

        jLSaldo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLSaldo.setText("0.0");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Valor da Transferencia: R$");

        jTFTransferencia.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jBVoltar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Selecionar Conta de Destino: ");

        jBTransferir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jBTransferir.setText("Transferir");
        jBTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBTransferir))
                    .addComponent(jLabel7)
                    .addComponent(jSConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBTransferir, jBVoltar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLSaldo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jSConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVoltar)
                    .addComponent(jBTransferir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransferirActionPerformed
        // TODO add your handling code here:
        int codContaDestino = Integer.valueOf(jSConta.getValue().toString());
        double saldoContaDestino = negocio.getDados(codContaDestino).getSaldo();
        
        double valorTransferencia = Double.valueOf(jTFTransferencia.getText());
        double saldoAtual = negocio.getDados(codContaAtual).getSaldo();
        double limiteAtual = negocio.getDados(codContaAtual).getLimite();
        double novoSaldo;
        double novoLimite;
        double saldoFinal;
        if(saldoAtual <= 0){
            if(valorTransferencia > limiteAtual){
                JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                jTFTransferencia.setText("");
            }else{
                novoSaldo = saldoAtual - valorTransferencia;
                novoLimite = limiteAtual - valorTransferencia;
                if(limiteAtual >= 0){
                    saldoFinal = novoSaldo;
                    jLSaldo.setText(String.valueOf(saldoFinal));
                    negocio.getDados(codContaAtual).setSaldo(saldoFinal);
                    negocio.getDados(codContaAtual).setLimite(novoLimite);
                    saldoContaDestino += valorTransferencia;
                    negocio.getDados(codContaDestino).setSaldo(saldoContaDestino);
                    jTFTransferencia.setText("");
                    JOptionPane.showMessageDialog(null,"Transferencia Realizada Com Sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                    jTFTransferencia.setText("");
                }
            }
        }else{
            novoSaldo = saldoAtual - valorTransferencia;
            if(novoSaldo >= 0){
                negocio.getDados(codContaAtual).setSaldo(novoSaldo);
                jLSaldo.setText(String.valueOf(novoSaldo));
                saldoContaDestino += valorTransferencia;
                negocio.getDados(codContaDestino).setSaldo(saldoContaDestino);
                jTFTransferencia.setText("");
                JOptionPane.showMessageDialog(null,"Transferencia Realizada Com Sucesso!");
            }else{
                novoLimite = limiteAtual + novoSaldo;
                saldoFinal = novoSaldo; 
                if(novoLimite >= 0){
                    negocio.getDados(codContaAtual).setSaldo(saldoFinal);
                    negocio.getDados(codContaAtual).setLimite(novoLimite);
                    saldoContaDestino += valorTransferencia;
                    negocio.getDados(codContaDestino).setSaldo(saldoContaDestino);
                    jTFTransferencia.setText("");
                    JOptionPane.showMessageDialog(null,"Transferencia Realizada Com Sucesso!");
                }else{
                    JOptionPane.showMessageDialog(null,"Erro! Nao há saldo nem limite necessário para copletar a trasação!");
                    jTFTransferencia.setText("");
                }
            }
        }
        jLSaldo.setText(String.valueOf(negocio.getDados(codContaAtual).getSaldo()));
    }//GEN-LAST:event_jBTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaTransferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContaTransferir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTransferir;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSConta;
    private javax.swing.JTextField jTFTransferencia;
    // End of variables declaration//GEN-END:variables
}
