/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsm.ia.se.conexaoInternet;

import javax.swing.JOptionPane;

/**
 *
 * @author patri
 */
public class InterfaceSE extends javax.swing.JFrame {

    private MaquinaInferencia maquinaInferencia;
    /**
     * Creates new form InterfaceSE
     */
    public InterfaceSE() {
        initComponents();
        this.maquinaInferencia = new MaquinaInferencia();
        oculta_componentes_exceto_cabo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Cabo = new javax.swing.JLabel();
        jLabel_Conectividade = new javax.swing.JLabel();
        jLabel_Erro = new javax.swing.JLabel();
        jLabel_Acesso_Negado = new javax.swing.JLabel();
        jLabel_Proxy = new javax.swing.JLabel();
        jLabel_Navegador = new javax.swing.JLabel();
        jLabel_Site = new javax.swing.JLabel();
        jLabel_Problema_IP = new javax.swing.JLabel();
        jLabel_DNS = new javax.swing.JLabel();
        jLabel_IP = new javax.swing.JLabel();
        jLabel_Download = new javax.swing.JLabel();
        jLabel_Lenta = new javax.swing.JLabel();
        jLabel_Outro = new javax.swing.JLabel();
        jLabel_Problema_IP2 = new javax.swing.JLabel();
        jCB_Cabo = new javax.swing.JComboBox<>();
        jCB_Conectividade = new javax.swing.JComboBox<>();
        jCB_Erro = new javax.swing.JComboBox<>();
        jCB_Acesso_Negado = new javax.swing.JComboBox<>();
        jCB_Proxy = new javax.swing.JComboBox<>();
        jCB_Navegador = new javax.swing.JComboBox<>();
        jCB_Site = new javax.swing.JComboBox<>();
        jCB_Problema_IP = new javax.swing.JComboBox<>();
        jCB_IP = new javax.swing.JComboBox<>();
        jCB_DNS = new javax.swing.JComboBox<>();
        jCB_Lenta = new javax.swing.JComboBox<>();
        jCB_Download = new javax.swing.JComboBox<>();
        jCB_Outro = new javax.swing.JComboBox<>();
        jBTN_Diagnosticar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Interface de usuário");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Auxilio ao diagnóstico de problemas de conexão a Internet");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Responda as seguintes questões", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        jLabel_Cabo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Cabo.setText("O cabo está conectado?");

        jLabel_Conectividade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Conectividade.setText("Tem um triângulo amarelo no ícone da internet próximo a hora?");

        jLabel_Erro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Erro.setText("Aparece a mensagem: não foi possível se conectar?");

        jLabel_Acesso_Negado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Acesso_Negado.setText("Aparece a mensagem: acesso negado ao cache ou url invalida?");

        jLabel_Proxy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Proxy.setText("Você sabe o que é proxy?");

        jLabel_Navegador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Navegador.setText("Qual navegador você usa?");

        jLabel_Site.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Site.setText("É só um site em específico que você não consegue acessar?");

        jLabel_Problema_IP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Problema_IP.setText("Execute a solução de problemas do Windows (botão direito no ícone que mostra a internet conectada->solução de problemas).");

        jLabel_DNS.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_DNS.setText("Apareceu problema no DNS?");

        jLabel_IP.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_IP.setText("Você sabe o que é IP?");

        jLabel_Download.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Download.setText("Você está fazendo download?");

        jLabel_Lenta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Lenta.setText("A Internet está lenta?");

        jLabel_Outro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Outro.setText("O seu problema foi questionado?");

        jLabel_Problema_IP2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel_Problema_IP2.setText("Deu problema no IP?");

        jCB_Cabo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jCB_Cabo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB_CaboActionPerformed(evt);
            }
        });
        jCB_Cabo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCB_CaboPropertyChange(evt);
            }
        });

        jCB_Conectividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Erro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Acesso_Negado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jCB_Acesso_Negado.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCB_Acesso_NegadoPropertyChange(evt);
            }
        });

        jCB_Proxy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Navegador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Firefox", "Chrome", "IE", "Outro" }));

        jCB_Site.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Problema_IP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_IP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_DNS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Lenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Download.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        jCB_Outro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Problema_IP)
                            .addComponent(jLabel_IP)
                            .addComponent(jLabel_DNS)
                            .addComponent(jLabel_Lenta)
                            .addComponent(jLabel_Download)
                            .addComponent(jLabel_Outro)
                            .addComponent(jLabel_Site)
                            .addComponent(jLabel_Navegador)
                            .addComponent(jLabel_Proxy)
                            .addComponent(jLabel_Acesso_Negado)
                            .addComponent(jLabel_Erro)
                            .addComponent(jLabel_Cabo)
                            .addComponent(jLabel_Conectividade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCB_Erro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Acesso_Negado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Download, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Lenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_DNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Problema_IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB_Conectividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCB_Cabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_Problema_IP2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Cabo)
                    .addComponent(jCB_Cabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Conectividade)
                    .addComponent(jCB_Conectividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Erro)
                    .addComponent(jCB_Erro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Acesso_Negado)
                    .addComponent(jCB_Acesso_Negado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Proxy)
                    .addComponent(jCB_Proxy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Navegador)
                    .addComponent(jCB_Navegador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Site)
                    .addComponent(jCB_Site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Problema_IP)
                    .addComponent(jCB_Problema_IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Problema_IP2)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel_IP)
                                                    .addComponent(jCB_IP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel_DNS))
                                            .addComponent(jCB_DNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Lenta))
                                    .addComponent(jCB_Lenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_Download))
                            .addComponent(jCB_Download, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_Outro))
                    .addComponent(jCB_Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBTN_Diagnosticar.setText("Diagnosticar");
        jBTN_Diagnosticar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_DiagnosticarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(jBTN_Diagnosticar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBTN_Diagnosticar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCB_Acesso_NegadoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCB_Acesso_NegadoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jCB_Acesso_NegadoPropertyChange
    
    private void oculta_componentes_exceto_cabo(){
        jLabel_Conectividade.setVisible(false);
        jCB_Conectividade.setVisible(false);
        jLabel_Acesso_Negado.setVisible(false);
        jCB_Acesso_Negado.setVisible(false);
        jLabel_DNS.setVisible(false);
        jCB_DNS.setVisible(false);
        jLabel_Download.setVisible(false);
        jCB_Download.setVisible(false);
        jLabel_Erro.setVisible(false);
        jCB_Erro.setVisible(false);
        jLabel_IP.setVisible(false);
        jCB_IP.setVisible(false);
        jLabel_Lenta.setVisible(false);
        jCB_Lenta.setVisible(false);
        jLabel_Navegador.setVisible(false);
        jCB_Navegador.setVisible(false);
        jLabel_Outro.setVisible(false);
        jCB_Outro.setVisible(false);
        jLabel_Problema_IP.setVisible(false);
        jLabel_Problema_IP2.setVisible(false);
        jCB_Problema_IP.setVisible(false);
        jLabel_Proxy.setVisible(false);
        jCB_Proxy.setVisible(false);
        jLabel_Site.setVisible(false);
        jCB_Site.setVisible(false);
    }
    
    private void envia_Dado_Cabo(){
        this.maquinaInferencia.getBaseConhecimento().setCabo(jCB_Cabo.getSelectedIndex());
    }
    
    private void envia_Dados(){
        this.maquinaInferencia.getBaseConhecimento().setConectividade(jCB_Conectividade.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setDns(jCB_DNS.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setDownload(jCB_Download.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setErro(jCB_Erro.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setIp(jCB_IP.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setLenta(jCB_Lenta.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setNavegador(jCB_Navegador.getSelectedItem().toString());
        this.maquinaInferencia.getBaseConhecimento().setOutro(jCB_Outro.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setProblema_IP(jCB_Problema_IP.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setProxy(jCB_Proxy.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setSite(jCB_Site.getSelectedIndex());
        this.maquinaInferencia.getBaseConhecimento().setAcesso_negado(jCB_Acesso_Negado.getSelectedIndex());
    }
    
    private void exibe_demais_opcoes(){
        jLabel_Conectividade.setVisible(true);
        jCB_Conectividade.setVisible(true);
        jLabel_Acesso_Negado.setVisible(true);
        jCB_Acesso_Negado.setVisible(true);
        jLabel_DNS.setVisible(true);
        jCB_DNS.setVisible(true);
        jLabel_Download.setVisible(true);
        jCB_Download.setVisible(true);
        jLabel_Erro.setVisible(true);
        jCB_Erro.setVisible(true);
        jLabel_IP.setVisible(true);
        jCB_IP.setVisible(true);
        jLabel_Lenta.setVisible(true);
        jCB_Lenta.setVisible(true);
        jLabel_Navegador.setVisible(true);
        jCB_Navegador.setVisible(true);
        jLabel_Outro.setVisible(true);
        jCB_Outro.setVisible(true);
        jLabel_Problema_IP.setVisible(true);
        jLabel_Problema_IP2.setVisible(true);
        jCB_Problema_IP.setVisible(true);
        jLabel_Proxy.setVisible(true);
        jCB_Proxy.setVisible(true);
        jLabel_Site.setVisible(true);
        jCB_Site.setVisible(true);
    }
    
    private void jCB_CaboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCB_CaboPropertyChange

    }//GEN-LAST:event_jCB_CaboPropertyChange

    private void jCB_CaboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB_CaboActionPerformed
        envia_Dado_Cabo();
        String resposta = this.maquinaInferencia.verifica_cabo();
        if(resposta != null){
            oculta_componentes_exceto_cabo();
            JOptionPane.showMessageDialog(null, resposta);
        }else{
            exibe_demais_opcoes();
        }
    }//GEN-LAST:event_jCB_CaboActionPerformed

    private void jBTN_DiagnosticarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_DiagnosticarActionPerformed
        envia_Dados();
        String resposta = this.maquinaInferencia.verifica_Dados();
        if(resposta != null){
            JOptionPane.showMessageDialog(null, resposta);
        }
    }//GEN-LAST:event_jBTN_DiagnosticarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceSE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTN_Diagnosticar;
    private javax.swing.JComboBox<String> jCB_Acesso_Negado;
    private javax.swing.JComboBox<String> jCB_Cabo;
    private javax.swing.JComboBox<String> jCB_Conectividade;
    private javax.swing.JComboBox<String> jCB_DNS;
    private javax.swing.JComboBox<String> jCB_Download;
    private javax.swing.JComboBox<String> jCB_Erro;
    private javax.swing.JComboBox<String> jCB_IP;
    private javax.swing.JComboBox<String> jCB_Lenta;
    private javax.swing.JComboBox<String> jCB_Navegador;
    private javax.swing.JComboBox<String> jCB_Outro;
    private javax.swing.JComboBox<String> jCB_Problema_IP;
    private javax.swing.JComboBox<String> jCB_Proxy;
    private javax.swing.JComboBox<String> jCB_Site;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Acesso_Negado;
    private javax.swing.JLabel jLabel_Cabo;
    private javax.swing.JLabel jLabel_Conectividade;
    private javax.swing.JLabel jLabel_DNS;
    private javax.swing.JLabel jLabel_Download;
    private javax.swing.JLabel jLabel_Erro;
    private javax.swing.JLabel jLabel_IP;
    private javax.swing.JLabel jLabel_Lenta;
    private javax.swing.JLabel jLabel_Navegador;
    private javax.swing.JLabel jLabel_Outro;
    private javax.swing.JLabel jLabel_Problema_IP;
    private javax.swing.JLabel jLabel_Problema_IP2;
    private javax.swing.JLabel jLabel_Proxy;
    private javax.swing.JLabel jLabel_Site;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
